### ISSUE TITLE
UnmodifiableMapMixin and others aren't Dart3-ready

### ISSUE THREAD

**Issue by oprypin** [dart-lang/collection#276]
`UnmodifiableMapMixin` should become a `mixin` or `mixin class`. Otherwise it is not ready for use with Dart 3 / `prefer_mixin`.
All usages of it are expected to be within a `with` clause. 

Others that I noticed are `NonGrowableListMixin`, `UnmodifiableSetMixin`

**Comment by lrhn** [comment]
Argh. My bad. Wrong issue tracker entirely. (Naming footgun!)

Yes, yes they should.

**Comment by oprypin** [comment]
Ping on this issue. I think this is high priority to resolve and make a release of this library ahead of Dart 3.

Also cc @mit-mit @devoncarew

**Comment by lrhn** [comment]
There is technically no reason to change anything, since pre-3.0 code classes can still be used as mixins without the `mixin` modifier.
It's only an issue if someone tries to interpret the pre-3.0 code as post-3.0 code, ignoring the languge-version of the pubspec.

The bigger issue is that solving this means migrating the package to 3.0 properly, which should, rightfully, mean a major version increment.

**Comment by dannnnthemannnn** [comment]
Hey all, I'm trying to use collections.dart and am getting errors like:

packages/collection/src/boollist.dart:231:50:
Error: The class 'NonGrowableListMixin' can't be used as a mixin because it isn't a mixin class nor a mixin.
class _NonGrowableBoolList extends BoolList with NonGrowableListMixin<bool> {
This is pulled in via transitive dependencies.

My dart version:

dart --version
Dart SDK version: 3.4.0 (stable) (Mon May 6 07:59:58 2024 -0700) on "macos_arm64"

I see this package says its SDK is ^3.1 in the pubspec.yaml. 

Am I doing something wrong or is there a way to get this to continue working? I am using the dart associated with the latest version of flutter

My build command is: dart run build_runner build --output=build

**Comment by dannnnthemannnn** [comment]
Ah I am using 1.18. So its not possible currently to use dart:collection with the current dart version? Curious how does flutter work when the current packaged dart version with flutter stable is 3.4?

**Comment by lrhn** [comment]
You should be able to use `package:collection` 1.18 with any SDK that supports language version 2.18. All 3.X SDKs supports that.

If you do so, you should not get any error.
Pre-3.0 `class`es with no superclass can be used as mixins, both by pre- and post-3.0 code. 

If it cannot, we have a bug.

I cannot reproduce the issue. Using tip-of-tree SDK, in a fresh dart package (`dart create coltest`) with an SDK version of ^3.3.0 and dependency `collection: 1.18.0`, the following code has no error:
```dart
import "dart:collection";
import "package:collection/collection.dart";

abstract class C extends ListBase<int> with NonGrowableListMixin<int> {}
```

Any chance you can show an entire compilable file that has the error, and/or check the language version of `package:collection` in `.dart_tool/package_config.json`?

**Comment by dannnnthemannnn** [comment]
I am building using build runner/dart2js. The language version in collection says 
```
{
  "name": "collection",
  "rootUri": "file:///Users/dannyfranklin/.pub-cache/git/collection-d51223f93e109408666606fbb13a37b79a1ec2c2/",
  "packageUri": "lib/",
  "languageVersion": "3.0"
},
```

I am building using `flutter pub run build_runner build --output=build`
and my build.

My build.yaml
```
targets:
  $default:
    sources:
      - "$package$"
      - "node/**"
      - "lib/**"
      - "js/**"
    builders:
      build_node_compilers|entrypoint:
        generate_for:
        - node/**
        options:
          compiler: dart2js
          # List any dart2js specific args here, or omit it.
          dart2js_args:
            - -O0
      json_serializable:
        options:
          explicit_to_json: true
```

My pubspec env:
```
environment:
  sdk: ">=2.18.0 <3.0.0"
```
